### ISSUE TITLE
problem with AVX2 and SSE3

### ISSUE THREAD

**Issue by iwanbk** [templexxx/reedsolomon#3]
First, thanks for your wonderful library, i have used it for quite some time and pretty happy with it.

I'm trying to use newer version of your library and found some issues:
- backward incompatible API : i suggest to fix the API
- it failed for the AVX2 and SSE3 optimization, see the errors below. `Base` mode is working good.

Error message on AVX2
```
goroutine 5 [running]:
runtime.throw(0x6c62fc, 0x5)
        /home/ibk/go/src/runtime/panic.go:596 +0x95 fp=0xc420045c80 sp=0xc420045c60
runtime.sigpanic()
        /home/ibk/go/src/runtime/signal_unix.go:297 +0x28c fp=0xc420045cd0 sp=0xc420045c80
github.com/templexxx/reedsolomon.mulAVX2(0xc42000af00, 0x20, 0x100, 0xc4200c2f00, 0x96, 0x258, 0xc42008fb80, 0x96, 0x96, 0x0, ...)
        /home/ibk/pathgo/src/github.com/templexxx/reedsolomon/avx2_amd64.s:27 +0x4e fp=0xc420045cd8 sp=0xc420045cd0
github.com/templexxx/reedsolomon.rsAVX2.matrixMul(0xc42000af00, 0x100, 0x100, 0x4, 0x2, 0x0, 0x96, 0xc4200a8090, 0x6, 0x6, ...)
        /home/ibk/pathgo/src/github.com/templexxx/reedsolomon/encode.go:70 +0x188 fp=0xc420045d48 sp=0xc420045cd8
github.com/templexxx/reedsolomon.rsAVX2.Encode(0xc42000af00, 0x100, 0x100, 0x4, 0x2, 0xc4200a8090, 0x6, 0x6, 0xc4200a8120, 0x6, ...)
        /home/ibk/pathgo/src/github.com/templexxx/reedsolomon/encode.go:12 +0x237 fp=0xc420045dd0 sp=0xc420045d48
github.com/templexxx/reedsolomon.(*rsAVX2).Encode(0xc420015710, 0xc4200a8090, 0x6, 0x6, 0xc4200a8120, 0x6, 0x6, 0x0, 0x6949e0)
        <autogenerated>:1 +0xbb fp=0xc420045e48 sp=0xc420045dd0
github.com/zero-os/0-stor-lib/distribution.(*Distribution).Encode(0xc4200ef440, 0xc4200c2f00, 0x258, 0x258, 0x0, 0x0, 0x0, 0x59671601, 0x21630978)
        /home/ibk/pathgo/src/github.com/zero-os/0-stor-lib/distribution/distribution.go:47 +0x3a9 fp=0xc420045f30 sp=0xc420045e48
github.com/zero-os/0-stor-lib/distribution.TestRoundTrip(0xc420068d00)
        /home/ibk/pathgo/src/github.com/zero-os/0-stor-lib/distribution/distribution_test.go:25 +0x112 fp=0xc420045fa8 sp=0xc420045f30
testing.tRunner(0xc420068d00, 0x6d6408)
        /home/ibk/go/src/testing/testing.go:657 +0x96 fp=0xc420045fd0 sp=0xc420045fa8
runtime.goexit()
        /home/ibk/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc420045fd8 sp=0xc420045fd0
created by testing.(*T).Run
        /home/ibk/go/src/testing/testing.go:697 +0x2ca

goroutine 1 [chan receive]:
testing.(*T).Run(0xc420068c30, 0x6c8640, 0xd, 0x6d6408, 0xc420055d20)
        /home/ibk/go/src/testing/testing.go:698 +0x2f4
testing.runTests.func1(0xc420068c30)
        /home/ibk/go/src/testing/testing.go:882 +0x67
testing.tRunner(0xc420068c30, 0xc420055de0)
        /home/ibk/go/src/testing/testing.go:657 +0x96
testing.runTests(0xc4200ef420, 0x818680, 0x1, 0x1, 0xc420055ed0)
        /home/ibk/go/src/testing/testing.go:888 +0x2c1
testing.(*M).Run(0xc420055f20, 0xc420055f20)
        /home/ibk/go/src/testing/testing.go:822 +0xfc
main.main()
        github.com/zero-os/0-stor-lib/distribution/_test/_testmain.go:42 +0xf7

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /home/ibk/go/src/runtime/asm_amd64.s:2197 +0x1
exit status 2
FAIL    github.com/zero-os/0-stor-lib/distribution      0.005s
```

error message on SSE3
```
panic: runtime error: slice bounds out of range [recovered]
        panic: runtime error: slice bounds out of range

goroutine 5 [running]:
testing.tRunner.func1(0xc420076ea0)
        /home/ibk/go/src/testing/testing.go:622 +0x29d
panic(0x67a2c0, 0x817f10)
        /home/ibk/go/src/runtime/panic.go:489 +0x2cf
github.com/templexxx/reedsolomon.rsSSSE3.matrixMul(0xc42000af00, 0x100, 0x100, 0x4, 0x2, 0x0, 0x96, 0xc4200b6090, 0x6, 0x6, ...)
        /home/ibk/pathgo/src/github.com/templexxx/reedsolomon/encode.go:88 +0x2b3
github.com/templexxx/reedsolomon.rsSSSE3.Encode(0xc42000af00, 0x100, 0x100, 0x4, 0x2, 0xc4200b6090, 0x6, 0x6, 0xc4200b6120, 0x6, ...)
        /home/ibk/pathgo/src/github.com/templexxx/reedsolomon/encode.go:39 +0x1a3
github.com/templexxx/reedsolomon.(*rsSSSE3).Encode(0xc420015710, 0xc4200b6090, 0x6, 0x6, 0xc4200b6120, 0x6, 0x6, 0x0, 0x6949e0)
        <autogenerated>:11 +0xbb
github.com/zero-os/0-stor-lib/distribution.(*Distribution).Encode(0xc4200fd440, 0xc4200d0f00, 0x258, 0x258, 0x0, 0x0, 0x0, 0x59671701, 0x1fe1f14b)
        /home/ibk/pathgo/src/github.com/zero-os/0-stor-lib/distribution/distribution.go:47 +0x3a9
github.com/zero-os/0-stor-lib/distribution.TestRoundTrip(0xc420076ea0)
        /home/ibk/pathgo/src/github.com/zero-os/0-stor-lib/distribution/distribution_test.go:25 +0x112
testing.tRunner(0xc420076ea0, 0x6d6400)
        /home/ibk/go/src/testing/testing.go:657 +0x96
created by testing.(*T).Run
        /home/ibk/go/src/testing/testing.go:697 +0x2ca
exit status 2
```

**Comment by iwanbk** [comment]
I found the issue for AVX2, the shard size need to be multiply of `LoopSizeAVX2`

**Comment by templexxx** [comment]
@iwanbk yeah... 

I mentioned the problem in README.  

Anyway, thank you for what your found!

I will fix it soon

**Comment by iwanbk** [comment]
> the shard size must be integral multiple of 256B (avx2) or 16B (ssse3), in practice, we always have a fixed shard size, and I'm too lazy to make it flexible

Oh, forgive my ignorance.

I don't think you need to fix it, these things are enough i think:
- give bigger & bold font in the readme
- mentioned it in godocs
